### ISSUE TITLE
Any way to do string comparison inside an if condition?

### ISSUE THREAD

**Issue by thecodrr** [rossmacarthur/upon#20]
Basically something like:

```
{% if site.config.theme  == "light" %}

{% else %}
    
{% endif %}
```

**Comment by rossmacarthur** [comment]
Currently the `upon` way to do this is with a filter. For example:

```rust
engine.add_filter("eq", str::eq);
```

And then in your template

```
{% if site.config.theme | eq: "light" %}

{% else %}
    
{% endif %}
```

**Comment by rossmacarthur** [comment]
I do think `==` and `!=` is a common enough operation that it is probably worth adding as a first class thing. I wanted to avoid adding stuff like `+` and `-` expressions because the templates get really complicated but I think boolean operators are probably fine.

I have opened https://github.com/rossmacarthur/upon/issues/21 to track this
